server:
  port: 5500
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instance-id:${random.value}}

spring:
  application:
    name: surgery-service
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true

  datasource:
    hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
    username: root
    password: Welcome12!@
    url: jdbc:mysql://localhost:3306/surgery_db
  cloud:
    stream:
      bindings:
        inputPersonInfo:
          destination: personInformationExchange
          group: personInformation_SurgeryQ
          binder: rabbit1
        outSurgeryAudit:
          destination: surgeryUpdateExchange
          binder: rabbit1
        surgeryAuditInput:
          destination: surgeryUpdateExchange
          group: surgeryAuditQ
          binder: rabbit1
#        theatreScheduleUpdateInput:
#          destination: theatreScheduleUpdateExchange
#          group: theatreScheduleUpdate_SurgeryQ
#          binder: rabbit1


      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest



  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        #  generate_statistics: true
        jdbc:
          batch_size: 4
        order_inserts: true

  logging:
    level:
      org:
        springframework:
          data:
            mongodb:
              core:
                MongoTemplate: DEBUG

  data:
    mongodb:
      database: surgery_db
      authentication-database: admin
      host: 192.168.1.100
      port: 1996
      username: shavantha
      password: Welcome12!@
      repositories:
        enabled: true

  zipkin:
    base-url: http://192.168.1.100:9411


resilience4j:
  circuitbreaker:
    instances:
      schedulerService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
        allow-health-indicator-to-fail: true
        register-health-indicator: true
      clinicalDataService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
        allow-health-indicator-to-fail: true
        register-health-indicator: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always

spring-doc:
  version: 1.0

token:
  secret: jguy5675hghgtrljkh
