spring:
  application:
    name: audit-service
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    stream:
      bindings:
        riskackoutchannel:
          destination: riskackexchange
          group: riskackq
          binder: rabbit1             
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest 
  data:
    mongodb:
      database: audit-documents
      authentication-database: admin
      host: 192.168.1.100
      username: shavantha
      password: Welcome12!@
      port: 1996
      repositories:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 5500
spring-doc:
  version: 1

token:
  secret: jguy5675hghgtrljkh
